package ap.world;

import ap.Game;
import ap.gfx.Assets;

public class JvPlayerHouse
{

	public JvPlayerHouse()
	{
		// Data
		Game.world.setName("JvPlayerHouse");
		Game.world.setLocation("My House - Jharva Village");
		Game.world.setGridScroll(false);
		
		// Dimensions
		Game.world.setGridWidth(42);
		Game.world.setGridHeight(23);
		
		// Background
		Game.world.setBackground();
		
		// Tiles
		Game.world.tileInit(Assets.tlsJharvaInterior[0], 0);
		
		Game.world.setTile(15, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(16, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(17, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(18, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(19, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(20, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(21, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(22, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(23, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(24, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(25, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(26, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(27, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(28, 9, Assets.tlsJharvaInterior[2], 1);
		Game.world.setTile(15, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(16, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(17, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(18, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(19, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(20, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(21, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(22, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(23, 10, Assets.tlsJharvaInterior[13], 1);
		Game.world.setTile(24, 10, Assets.tlsJharvaInterior[23], 1);
		Game.world.setTile(25, 10, Assets.tlsJharvaInterior[15], 1);
		Game.world.setTile(26, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(27, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(28, 10, Assets.tlsJharvaInterior[10], 1);
		Game.world.setTile(14, 11, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 11, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 11, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 12, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 12, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 12, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 13, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 13, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 13, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 14, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 14, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 14, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 15, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 15, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 15, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 16, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 16, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 16, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 17, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 17, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 17, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(14, 18, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(16, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(17, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(18, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(19, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(20, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(21, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(22, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(23, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(24, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(25, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(26, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(27, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(28, 18, Assets.tlsJharvaInterior[1], 0);
		Game.world.setTile(29, 18, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(15, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(16, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(17, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(18, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(19, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(20, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(21, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(22, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(23, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(24, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(25, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(26, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(27, 19, Assets.tlsJharvaInterior[0], 1);
		Game.world.setTile(28, 19, Assets.tlsJharvaInterior[0], 1);
		
		// Portals
		Game.world.setPortal("Collide", 24, 10, "JvPlayerBedroom", 25, 11, "S");
		Game.world.setPortal("Collide", 21, 19, "JvExterior", 50, 43, "S", 29, 32);
		Game.world.setPortal("Collide", 22, 19, "JvExterior", 50, 43, "S", 29, 32);
	}
}